---
- name: add repository
  apt_repository: repo='ppa:ondrej/php5' state=present

- name: install php packages
  apt: pkg={{ item }} state=latest force=yes update_cache=yes
  with_items:
    - php5-cli
    - php5-fpm
    - php5-intl
    - php5-common
    - php5-curl
    - php5-dev
    - php5-xdebug
    - php5-mysql
    - php5-mcrypt
    - php5-mysql
    - php5-memcache
  notify: restart php-fpm


